#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Shaman VPC | Devkit Utility' 
  hosts: local
  vars:
    module: "shaman-vpc"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/shaman-vpc"
    ansible_name_module_cloud: " {{ module }}"
  vars_files:
    - vars/global.yml

#  vars_prompt:
#    - name: cloud_region
#      prompt: "Please enter your AWS region"
#      private: no
#    - name: cluster_name
#      prompt: "Please enter your AWS VPC Name"
#      private: no
#    - name: aws_access_key
#      prompt: "Please enter your AWS Access Key ID"
#      private: no
#    - name: aws_secret_key
#      prompt: "Please enter your AWS Access Key Secret"
#      private: no

  tasks:

    ####### Terraform Apply
    - name: '{{ ansible_name_module_cloud }} | terraform | apply'
      terraform:
        project_path: "{{ tf_module_path }}"
        variables_file: "{{ tf_module_path }}/global.tfvars"
        force_init: true
        state: absent
      register: tf_output
