#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Devkit | Build VPC'
  hosts: local
  vars:
    module: "build"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/devkit-vpc"
    ansible_name_module: " Konductor | Devkit VPC | {{ module }}"
  vars_files:
    - vars/global.yml

  tasks:

    - name: '{{ ansible_name_module }} | file | Create ~/.aws'
      file:
        path: "/root/.aws"
        state: directory

    ####### Stage Variables & AWS Creds
    - name: '{{ ansible_name_module }} | template | Terraform Vars & aws credentials'
      template:
        src: "{{ item.name }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - { mode: '755', name: "templates/terraform/global.tfvars.j2", dest: "{{ tf_module_path }}/global.tfvars"}
        - { mode: '600', name: "templates/aws/credentials.j2", dest: "{{ local_home }}/.aws/credentials"}
